import mssql from 'mssql'
import { ColumnDefinition } from "whiskey-sql/lib/components/columnDefinition"

export function DeviceTable():ColumnDefinition[] {
    let Columns:ColumnDefinition[] = []
    
    Columns.push(new ColumnDefinition('DeviceName', mssql.VarChar(255), false, true))
    Columns.push(new ColumnDefinition('DeviceIsActive', mssql.Bit, false, true))
    Columns.push(new ColumnDefinition('DeviceFirstObserved', mssql.DateTime2))
    Columns.push(new ColumnDefinition('DeviceLastObserved', mssql.DateTime2))

    // Active Directory details
    Columns.push(new ColumnDefinition('ActiveDirectoryDN', mssql.VarChar(255), true, true))
    Columns.push(new ColumnDefinition('ActiveDirectoryDNSHostName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryOperatingSystem', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryOperatingSystemVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryLogonCount', mssql.Int))
    Columns.push(new ColumnDefinition('ActiveDirectoryWhenCreated', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryWhenChanged', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryLastLogon', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryPwdLastSet', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryLastLogonTimestamp', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryLastSeen', mssql.DateTime2))

    // Azure Active Directory details
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeviceId', mssql.VarChar(255), true, true))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryId', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeviceCategory', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeviceMetadata', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeviceOwnership', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeviceVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDomainName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryEnrollmentProfileType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryEnrollmentType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryExternalSourceName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryManagementType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryManufacturer', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryMDMAppId', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryModel', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryProfileType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectorySourceType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryTrustType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOperatingSystem', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOperatingSystemVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeletedDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryApproximateLastSignInDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryComplianceExpirationDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryCreatedDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOnPremisesLastSyncDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryRegistrationDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryLastSeen', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOnPremisesSyncEnabled', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryAccountEnabled', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryIsCompliant', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryIsManaged', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryIsRooted', mssql.Bit))

    // Azure MDM details
    Columns.push(new ColumnDefinition('AzureMDMId', mssql.VarChar(255), true, true))
    Columns.push(new ColumnDefinition('AzureMDMDeviceName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMUserId', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMDeviceOwnerType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMComplianceState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMJailBroken', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMManagementAgent', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMOperatingSystem', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMOperatingSystemVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMEASDeviceID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMDeviceEnrollmentType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMActivationLockBypassCode', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMEmailAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMAzureADDeviceID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMDeviceRegistrationState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMDeviceCategoryDisplayName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMExchangeAccessState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMExchangeAccessStateReason', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMRemoteAssistanceSessionUrl', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMRemoteAssistanceErrorDetails', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMUserPrincipalName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMModel', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMManufacturer', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMIMEI', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMSerialNumber', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMPhoneNumber', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMAndroidSecurityPatchLevel', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMUserDisplayName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMConfigurationManagerClientEnabledFeatures', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMWiFiMACAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMDeviceHealthAttestationState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMSubscriberCarrier', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMMEID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMPartnerReportedThreatState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMRequireUserEnrollmentApproval', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMICCID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMUDID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMNotes', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMEthernetMacAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureMDMTotalStorageSpaceInBytes', mssql.BigInt))
    Columns.push(new ColumnDefinition('AzureMDMFreeStorageSpaceInBytes', mssql.BigInt))
    Columns.push(new ColumnDefinition('AzureMDMPhysicalMemoryInBytes', mssql.BigInt))
    Columns.push(new ColumnDefinition('AzureMDMEnrolledDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMLastSyncDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMEASActivationDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMExchangeLastSuccessfulSyncDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMComplianceGracePeriodExpirationDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMManagementCertificateExpirationDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMLastSeen', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureMDMIsEASActivated', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureMDMIsAzureADRegistered', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureMDMIsSupervised', mssql.Bit))
    Columns.push(new ColumnDefinition('AzureMDMIsEncrypted', mssql.Bit))

    // Connectwise details
    Columns.push(new ColumnDefinition('ConnectwiseId', mssql.VarChar(255), true, true))
    Columns.push(new ColumnDefinition('ConnectwiseDeviceType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseLocation', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseClient', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseOperatingSystem', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseOperatingSystemVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseDomainName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseAgentVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseComment', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseIpAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseMacAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseLastUserName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseStatus', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseSerialNumber', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseManufacturer', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseModel', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseDescription', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ConnectwiseTotalMemory', mssql.BigInt))
    Columns.push(new ColumnDefinition('ConnectwiseFreeMemory', mssql.BigInt))
    Columns.push(new ColumnDefinition('ConnectwiseFirstSeen', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ConnectwiseLastObserved', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ConnectwiseWindowsUpdateDate', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ConnectwiseAntivirusDefinitionDate', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ConnectwiseAssetDate', mssql.DateTime2))

    // Crowdstrike details
    Columns.push(new ColumnDefinition('CrowdStrikeDeviceId', mssql.VarChar(255), true, true))
    Columns.push(new ColumnDefinition('CrowdStrikeCID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeAgentVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeBIOSManufacturer', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeBIOSVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeExternalIP', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeMACAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeLocalIP', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeMachineDomain', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeMajorVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeMinorVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeOSVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeOSBuild', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikePlatformName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeReducedFunctionalityMode', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeProductTypeDesc', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeProvisionStatus', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeSerialNumber', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeServicePackMajor', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeServicePackMinor', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeStatus', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeSystemManufacturer', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeSystemProductName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeKernelVersion', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('CrowdStrikeFirstSeenDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('CrowdStrikeLastSeenDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('CrowdStrikeModifiedDateTime', mssql.DateTime2))

    return Columns
}