import mssql from 'mssql'
import { ColumnDefinition } from "whiskey-sql/lib/components/columnDefinition"

export function UserTable():ColumnDefinition[] {
    let Columns:ColumnDefinition[] = []
    Columns.push(new ColumnDefinition('EmailAddress', mssql.VarChar(255), true, true))
    Columns.push(new ColumnDefinition('LastObserved', mssql.DateTime2))
    Columns.push(new ColumnDefinition('IsActive', mssql.Bit, false))

    Columns.push(new ColumnDefinition('ObservedByActiveDirectory', mssql.Bit, false, true))
    Columns.push(new ColumnDefinition('ObservedByAzureActiveDirectory', mssql.Bit, false, true))
    
    Columns.push(new ColumnDefinition('ActiveDirectoryDN', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryCN', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectorySN', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryCountry', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryCity', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryTitle', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryOffice', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryTelephoneNumber', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryGivenName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryDisplayName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryDepartment', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryStreetAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryUserName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryEmployeeID', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectorySAMAccountName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryPrincipalName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryUserMail', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('ActiveDirectoryLogonCount', mssql.Int))
    Columns.push(new ColumnDefinition('ActiveDirectoryCreatedDate', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryChangedDate', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryBadPasswordTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryLastLogon', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryLastLogonTimestamp', mssql.DateTime2))
    Columns.push(new ColumnDefinition('ActiveDirectoryLastSeen', mssql.DateTime2))
    
    Columns.push(new ColumnDefinition('AzureActiveDirectoryAccountEnabled', mssql.Bit, true, true))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryUserPrincipalName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryId', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryBusinessPhone', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDisplayName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryGivenName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryJobTitle', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryMobilePhone', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOfficeLocation', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectorySurname', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryAssignedPlans', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryCity', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryCountry', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryCreationType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDepartment', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryEmployeeHireDate', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryEmployeeId', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryEmployeeOrgData', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryEmployeeType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOnPremisesDistinguishedName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOnPremisesDomainName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOnPremisesSamAccountName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryOnPremisesUserPrincipalName', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryPasswordPolicies', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryPostalCode', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryState', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryStreetAddress', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryUserType', mssql.VarChar(255)))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryCreatedDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryDeletedDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryLastPasswordChangeDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryLastSignInDateTime', mssql.DateTime2))
    Columns.push(new ColumnDefinition('AzureActiveDirectoryLastSeen', mssql.DateTime2))
    return Columns
}